name: m_two
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

# required to store/read/edit/delete data locally
  path_provider: ^2.0.11
# chosen state management solution
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1

  # no more packages :(

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 
  mobx_codegen: 
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
